# Generated by Django 6.0.2 on 2026-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_application_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='exe_file',
            field=models.FileField(blank=True, null=True, upload_to='exe/'),
        ),
    ]
