# Generated by Django 6.0.2 on 2026-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='apps/apk/')),
                ('exe_file', models.FileField(blank=True, null=True, upload_to='apps/exe/')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Paramètre utilisateur', 'verbose_name_plural': 'Paramètres utilisateurs'},
        ),
    ]
